### PR TITLE
Setup frontender on travis.

### PR DESCRIPTION
**Pull request by bayleedev**
@nwp we paired to get these simple files working. Just needing you to enable travis on both sides of the project! [:

### CODE REVIEW

**Comment by nwp** [comment]
Done.

**Comment by bayleedev** [comment]
Thanks @nwp, just waiting on travis to kick us off! The free version is a little slow. ]:

**Comment by bayleedev** [comment]
Check it out! I just did another push and we are just waiting in line now [:

https://travis-ci.org/mdx-dev/li3_frontender/builds/22022101

**Comment by bayleedev** [comment]
Green! Merge!

merge

**Pull request merged**
